version: 1.0
config:
- stage: boot
  tasks:
  - task: extendRootPartition
- stage: preReady
  tasks:
  - task: activateWindows
    inputs:
      activation:
        type: amazon
  - task: setDnsSuffix
    inputs:
      suffixes:
      - $REGION.ec2-utilities.amazonaws.com
  - task: setAdminAccount
    inputs:
      password:
        type: random
  - task: setWallpaper
    inputs:
      attributes:
      - instanceId
      - privateIpAddress
      - publicIpAddress
      - instanceSize
      - memory
      instanceTags: AllTags
      path: C:\s3-downloads\Scripts_Installation\Ec2Wallpaper.jpg
- stage: postReady
  tasks:
  - task: startSsm
